import { NextResponse } from "next/server";
import { createHash } from "crypto";

import { prisma } from "@/lib/prisma";

export const runtime = "nodejs";

function hashVerificationToken(
  token: string
) {
  return createHash("sha256")
    .update(token)
    .digest("hex");
}

export async function GET(
  request: Request
) {
  try {
    const url = new URL(request.url);

    const token =
      url.searchParams.get("token")?.trim() ||
      "";

    /* =========================
       TOKEN REQUIRED
    ========================= */

    if (!token) {
      return NextResponse.json(
        {
          success: false,
          code: "TOKEN_REQUIRED",
          message:
            "Email verification token is required.",
        },
        { status: 400 }
      );
    }

    /* =========================
       TOKEN FORMAT
    ========================= */

    /*
     * Tokens generated by randomBytes(32)
     * are 64 hexadecimal characters.
     */

    if (!/^[a-f0-9]{64}$/i.test(token)) {
      return NextResponse.json(
        {
          success: false,
          code: "INVALID_TOKEN",
          message:
            "This email verification link is invalid.",
        },
        { status: 400 }
      );
    }

    /* =========================
       HASH TOKEN
    ========================= */

    const tokenHash =
      hashVerificationToken(token);

    /* =========================
       FIND REQUEST
    ========================= */

    const emailChangeRequest =
      await prisma.emailChangeVerification.findUnique(
        {
          where: {
            verificationTokenHash:
              tokenHash,
          },

          include: {
            user: true,
          },
        }
      );

    if (!emailChangeRequest) {
      return NextResponse.json(
        {
          success: false,
          code: "TOKEN_NOT_FOUND",
          message:
            "This email verification link is invalid or has already been used.",
        },
        { status: 404 }
      );
    }

    /* =========================
       TOKEN EXPIRY
    ========================= */

    if (
      !emailChangeRequest.verificationTokenExpiresAt ||
      new Date() >
        emailChangeRequest.verificationTokenExpiresAt
    ) {
      /*
       * Invalidate expired token.
       */

      await prisma.emailChangeVerification.update(
        {
          where: {
            id:
              emailChangeRequest.id,
          },

          data: {
            verificationTokenHash:
              null,

            verificationTokenExpiresAt:
              null,

            newEmailVerified:
              false,
          },
        }
      );

      return NextResponse.json(
        {
          success: false,
          code: "TOKEN_EXPIRED",
          message:
            "This email verification link has expired. Please request a new verification email.",
        },
        { status: 410 }
      );
    }

    /* =========================
       CURRENT EMAIL STATE
    ========================= */

    if (
      emailChangeRequest.currentEmail !==
      emailChangeRequest.user.email
    ) {
      /*
       * The user's email changed through
       * another process, so this pending
       * request is no longer valid.
       */

      await prisma.emailChangeVerification.update(
        {
          where: {
            id:
              emailChangeRequest.id,
          },

          data: {
            verificationTokenHash:
              null,

            verificationTokenExpiresAt:
              null,

            newEmailVerified:
              false,
          },
        }
      );

      return NextResponse.json(
        {
          success: false,
          code:
            "EMAIL_CHANGE_STATE_INVALID",
          message:
            "This email change request is no longer valid. Please start the process again.",
        },
        { status: 409 }
      );
    }

    /* =========================
       NEW EMAIL
    ========================= */

    const newEmail =
      emailChangeRequest.newEmail
        .trim()
        .toLowerCase();

    if (!newEmail) {
      return NextResponse.json(
        {
          success: false,
          code:
            "INVALID_NEW_EMAIL",
          message:
            "The new email address is invalid.",
        },
        { status: 400 }
      );
    }

    /* =========================
       CURRENT EMAIL CHECK
    ========================= */

    if (
      newEmail ===
      emailChangeRequest.user.email
        .toLowerCase()
    ) {
      return NextResponse.json(
        {
          success: false,
          code: "SAME_EMAIL",
          message:
            "The new email must be different from the current email.",
        },
        { status: 400 }
      );
    }

    /* =========================
       EMAIL AVAILABILITY
    ========================= */

    const existingUser =
      await prisma.user.findUnique({
        where: {
          email: newEmail,
        },
      });

    if (
      existingUser &&
      existingUser.id !==
        emailChangeRequest.userId
    ) {
      /*
       * Someone else claimed the
       * requested email after the
       * verification process started.
       */

      await prisma.emailChangeVerification.update(
        {
          where: {
            id:
              emailChangeRequest.id,
          },

          data: {
            verificationTokenHash:
              null,

            verificationTokenExpiresAt:
              null,

            newEmailVerified:
              false,
          },
        }
      );

      return NextResponse.json(
        {
          success: false,
          code:
            "EMAIL_ALREADY_IN_USE",
          message:
            "This email address is now associated with another account.",
        },
        { status: 409 }
      );
    }

    /* =========================
       TRANSACTION
    ========================= */

    const updatedUser =
      await prisma.$transaction(
        async (tx) => {
          /*
           * Re-check availability inside
           * the transaction before changing
           * the unique email field.
           */

          const conflictingUser =
            await tx.user.findUnique({
              where: {
                email: newEmail,
              },
            });

          if (
            conflictingUser &&
            conflictingUser.id !==
              emailChangeRequest.userId
          ) {
            throw new Error(
              "EMAIL_ALREADY_IN_USE"
            );
          }

          /*
           * Update the actual account email.
           *
           * This is the FIRST point in the
           * complete flow where User.email
           * changes.
           */

          const updated =
            await tx.user.update({
              where: {
                id:
                  emailChangeRequest.userId,
              },

              data: {
                email: newEmail,
                emailVerified: true,
              },
            });

          /*
           * Invalidate the verification
           * token immediately so it cannot
           * be reused.
           */

          await tx.emailChangeVerification.update(
            {
              where: {
                id:
                  emailChangeRequest.id,
              },

              data: {
                verificationTokenHash:
                  null,

                verificationTokenExpiresAt:
                  null,

                newEmailVerified:
                  false,
              },
            }
          );

          return updated;
        }
      );

    /* =========================
       SUCCESS
    ========================= */

    return NextResponse.json(
      {
        success: true,

        code:
          "EMAIL_CHANGED_SUCCESSFULLY",

        message:
          "Your email address has been changed and verified successfully.",

        user: {
          id:
            updatedUser.id,

          firstName:
            updatedUser.firstName,

          surname:
            updatedUser.surname,

          email:
            updatedUser.email,

          emailVerified:
            updatedUser.emailVerified,
        },
      },

      { status: 200 }
    );
  } catch (error) {
    console.error(
      "Email change confirmation error:",
      error
    );

    if (
      error instanceof Error &&
      error.message ===
        "EMAIL_ALREADY_IN_USE"
    ) {
      return NextResponse.json(
        {
          success: false,
          code:
            "EMAIL_ALREADY_IN_USE",
          message:
            "This email address is already in use.",
        },
        { status: 409 }
      );
    }

    return NextResponse.json(
      {
        success: false,
        code:
          "EMAIL_CONFIRMATION_ERROR",
        message:
          "Something went wrong while confirming your new email.",
      },
      { status: 500 }
    );
  }
}